networks:
  ridemesh-network:
    driver: bridge

volumes:
  rabbitmq_data:

services:
  # --- INFRASTRUCTURE DEPENDENCY ---
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ridemesh-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  # --- AUTH SERVICE ---
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: ridemesh-auth-service:v1
    container_name: auth-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=${MONGO_URI_AUTH}
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_SECRET_KEY_FOR_REFRESHTOKEN=${JWT_SECRET_KEY_FOR_REFRESHTOKEN}
      - RIDER_SERVICE_URL=http://user-service:5002/api/v1/riders/internal
    networks:
      - ridemesh-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  # --- USER SERVICE ---
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: ridemesh-user-service:v1
    container_name: user-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=${MONGO_URI_USER}
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - AUTH_SERVICE_URL=http://auth-service:5001/api/v1/auth
    networks:
      - ridemesh-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  # --- DRIVER SERVICE ---
  driver-service:
    build:
      context: ./driver-service
      dockerfile: Dockerfile
    image: ridemesh-driver-service:v1
    container_name: driver-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGO_URI=${MONGO_URI_DRIVER}
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - AUTH_SERVICE_URL=http://auth-service:5001/api/v1/auth
    networks:
      - ridemesh-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  # --- RIDE SERVICE ---
  ride-service:
    build:
      context: ./ride-service
      dockerfile: Dockerfile
    image: ridemesh-ride-service:v1
    container_name: ride-service
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - MONGO_URI=${MONGO_URI_RIDE}
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DRIVER_SERVICE_URL=http://driver-service:5003/api/v1/drivers/internal
      - RIDER_SERVICE_URL=http://user-service:5002/api/v1/riders/internal
      - NOTIFICATION_SERVICE_URL=http://notification-service:5005/api/v1/notifications/internal
    networks:
      - ridemesh-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  # --- NOTIFICATION SERVICE ---
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    image: ridemesh-notification-service:v1
    container_name: notification-service
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - MONGO_URI=${MONGO_URI_NOTIF}
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
    networks:
      - ridemesh-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  # --- API GATEWAY ---
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: ridemesh-api-gateway:v1
    container_name: api-gateway
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - CLIENT_URL=${CLIENT_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AUTH_SERVICE_URL=http://auth-service:5001/api/v1/auth
      - USER_SERVICE_URL=http://user-service:5002/api/v1/riders
      - DRIVER_SERVICE_URL=http://driver-service:5003/api/v1/drivers
      - RIDE_SERVICE_URL=http://ride-service:5004/api/v1/rides
      - NOTIFICATION_SERVICE_URL=http://notification-service:5005/api/v1/notifications
      - PAYMENT_SERVICE_URL=http://localhost:5006/api/v1/payment
    networks:
      - ridemesh-network
    depends_on:
      - auth-service
      - user-service
      - driver-service
      - ride-service
      - notification-service
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ridemesh-frontend:v1
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - api-gateway
    networks:
      - ridemesh-network
    restart: on-failure